name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  packages: write

jobs:
  # First, build all binaries
  build:
    name: Build Binaries
    uses: ./.github/workflows/build-binaries.yml
    with:
      upload-artifacts: true

  # Then create the release
  release:
    name: Create Release
    needs: build
    uses: ./.github/workflows/create-release.yml
    with:
      tag: ${{ github.event.inputs.tag }}
      prerelease: ${{ github.event.inputs.prerelease }}
      event_name: ${{ github.event_name }}
      ref_name: ${{ github.ref_name }}
    secrets: inherit

  # Call Docker publishing workflow
  docker:
    name: Publish Docker Image
    needs: [build, release]
    if: ${{ !cancelled() && needs.release.result == 'success' }}
    uses: ./.github/workflows/publish.docker.yml
    with:
      tag:  ${{ github.event.inputs.tag }}
    secrets: inherit

  # Call NPM publishing workflow  
  publish-npm:
    name: Publish NPM Package
    needs: [build, release]
    if: ${{ !cancelled() && needs.release.result == 'success' }}
    uses: ./.github/workflows/publish.npm.yml
    secrets: inherit
